#!/bin/bash
sudo apt-get install python-pip curl jq
sudo pip install unicodecsv pyusb
sudo chmod +x md380cp
cd $HOME/MD380-Codeplug-Maker/c
make
cp $HOME/MD380-Codeplug-Maker/c/out/rdt2csv $HOME/MD380-Codeplug-Maker/
rm -r $HOME/MD380-Codeplug-Maker/c/out
cd $HOME/MD380-Codeplug-Maker
./md380cp -h

